API

The API is currently at version 1, so all documented paths are currently accessible via

 /api/v1

== Projects

=== Get All Projects

 GET project/:subject:

Retrieve all the projects belonging to the subject

[source,javascript]
Status: 200 OK
{
    [
        {
            "name": "projectName",
	    "uri": "https://api.huskydocs.com/project/jim/projectName"
        },
	{
            "name": "projectName2",
	    "uri": "https://api.huskydocs.com/project/jim/projectName2"
	}
    ]
}

=== Get Project

 GET /project/:subject:/:project:

Retrieve information regarding an individial project

[source,javascript]
Status: 200 OK
{
    "name": "projectName",
    "description": "Project Description"
}

=== Create Project

 PUT /project/:subject:/:project:

Create a Project that will belong to the specified user

[source,javascript]
{
    "description": "Project Description"
}

[source,javascript]
Status: 201 Created
{
    "name": "projectName",
    "description": "Project Description"
}

=== Delete Project

 DELETE /project/:subject:/:project:

Remove a Project and all content belonging to it

[source,javascript]
Status: 204 No Content

== Documents

=== Get All Documents

 GET document/:subject:/:project:

Retrieve all the documents belonging to the project

[source,javascript]
Status: 200 OK
{
    [
        {
            "name": "documentName",
	    "uri": "https://api.huskydocs.com/document/jim/projectName/documentName"
        },
	{
            "name": "documentName2",
	    "uri": "https://api.huskydocs.com/document/jim/projectName/documentName2"
	}
    ]
}

=== Get Document

 GET /document/:subject:/:project:/:document:

Retrieve the contents of a document

[source,javascript]
Status: 200 OK
= Document Title
Some text

=== Create Document

 PUT /document/:subject:/:project:/:document:

Create a new document within the project

[source,javascript]
----
= Document Title
Some text
----

[source,javascript]
Status: 201 Created

=== Update Document

 POST /document/:subject:/:project:/:document:

Update the contents of an existing document

[source,javascript]
----
= Document Title
Some text
----

[source,javascript]
Status: 204 No Content

=== Delete Document

 DELETE /document/:subject:/:project:/:document:

Remove a document from a project

[source,javascript]
Status: 204 No Content
